"""
PDF Export module for ComicCraft using fpdf2.
Creates a printable, multi-panel comic book publication document.
"""

import os
import uuid
import datetime
import logging
from pathlib import Path
from typing import Optional

from .config import settings
from .schemas import ComicStory, StoryGenerationRequest

logger = logging.getLogger(__name__)


def generate_pdf(story: ComicStory, req: StoryGenerationRequest) -> str:
    """
    Creates a styled 5-panel comic book PDF document and saves it to static/exports/.
    Returns the web URL path to the generated PDF.
    """
    settings.init_dirs()

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_suffix = uuid.uuid4().hex[:6]
    pdf_filename = f"comiccraft_{timestamp}_{unique_suffix}.pdf"
    pdf_path = settings.exports_dir / pdf_filename

    try:
        from fpdf import FPDF

        class ComicPDF(FPDF):
            def header(self):
                # Comic strip header banner
                self.set_fill_color(24, 28, 42)
                self.rect(0, 0, 210, 16, "F")
                self.set_font("Helvetica", "B", 10)
                self.set_text_color(245, 197, 24)
                self.set_xy(10, 3)
                self.cell(190, 10, "COMICCRAFT • AI COMIC STORY CREATOR", 0, 0, "C")
                self.ln(16)

            def footer(self):
                self.set_y(-12)
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(130, 140, 160)
                self.cell(0, 10, f"Page {self.page_no()} | Generated by ComicCraft with Gemini AI", 0, 0, "C")

        pdf = ComicPDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title Page / Banner
        pdf.add_page()
        pdf.set_fill_color(15, 18, 28)
        pdf.rect(10, 20, 190, 36, "F")

        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(255, 255, 255)
        pdf.set_xy(15, 24)
        pdf.cell(180, 10, story.title.encode('latin-1', 'replace').decode('latin-1'), 0, 1, "C")

        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(200, 215, 240)
        meta_str = f"Starring: {req.character_name}  |  Setting: {req.setting}  |  Tone: {req.tone}  |  Style: {req.art_style}"
        pdf.cell(180, 7, meta_str.encode('latin-1', 'replace').decode('latin-1'), 0, 1, "C")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(245, 197, 24)
        pdf.cell(180, 6, "FIVE-PANEL CHRONICLE", 0, 1, "C")
        pdf.ln(10)

        # Iterate over all 5 panels
        for panel in story.panels:
            # Check remaining vertical space; if low, add new page
            if pdf.get_y() > 210:
                pdf.add_page()

            # Panel Frame Container
            start_y = pdf.get_y()

            # Panel Header Tab
            pdf.set_fill_color(245, 197, 24)
            pdf.rect(10, start_y, 45, 7, "F")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(15, 15, 20)
            pdf.set_xy(12, start_y + 1)
            pdf.cell(40, 5, f"PANEL #{panel.panel_number}", 0, 0, "L")

            # Title
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(30, 40, 60)
            pdf.set_xy(60, start_y + 1)
            clean_title = panel.title.encode('latin-1', 'replace').decode('latin-1')
            pdf.cell(135, 5, clean_title, 0, 1, "L")
            pdf.ln(4)

            panel_body_y = pdf.get_y()

            # Embed Panel Image if available on disk
            img_width = 85
            img_height = 57
            image_placed = False

            if panel.image_url:
                local_rel = panel.image_url.lstrip("/")
                local_path = settings.base_dir / local_rel
                if local_path.exists():
                    try:
                        pdf.image(str(local_path), x=12, y=panel_body_y, w=img_width, h=img_height)
                        image_placed = True
                    except Exception as err:
                        logger.warning("Could not embed image %s into PDF: %s", local_path, err)

            if not image_placed:
                # Draw placeholder box
                pdf.set_fill_color(240, 242, 248)
                pdf.rect(12, panel_body_y, img_width, img_height, "F")
                pdf.set_xy(15, panel_body_y + 20)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(100, 110, 130)
                pdf.cell(img_width, 10, f"[Illustration: Panel {panel.panel_number}]", 0, 0, "C")

            # Right Side Text Column (Caption, Narration, Dialogue, Scene)
            text_x = 104
            text_w = 96
            pdf.set_xy(text_x, panel_body_y)

            # Caption (Top comic box style)
            if panel.caption:
                pdf.set_fill_color(255, 252, 230)
                pdf.set_draw_color(210, 180, 50)
                caption_text = f"CAPTION: {panel.caption}".encode('latin-1', 'replace').decode('latin-1')
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(80, 60, 10)
                pdf.multi_cell(text_w, 4.5, caption_text, border=1, fill=True)
                pdf.ln(1.5)

            # Narration
            if panel.narration:
                pdf.set_x(text_x)
                pdf.set_font("Helvetica", "I", 8.5)
                pdf.set_text_color(50, 60, 80)
                narration_text = f"Narration: \"{panel.narration}\"".encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(text_w, 4, narration_text)
                pdf.ln(1.5)

            # Dialogue Speech Bubbles
            if panel.dialogue:
                for line in panel.dialogue:
                    pdf.set_x(text_x)
                    pdf.set_fill_color(244, 246, 250)
                    pdf.set_draw_color(180, 190, 210)
                    dial_text = f" {line} ".encode('latin-1', 'replace').decode('latin-1')
                    pdf.set_font("Helvetica", "B", 8)
                    pdf.set_text_color(20, 24, 36)
                    pdf.multi_cell(text_w, 4.5, dial_text, border=1, fill=True)
                    pdf.ln(1)

            # Scene Description Note
            if panel.scene_description:
                pdf.set_x(text_x)
                pdf.set_font("Helvetica", "", 7.5)
                pdf.set_text_color(120, 130, 150)
                scene_text = f"Scene: {panel.scene_description}".encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(text_w, 3.5, scene_text)

            # Bottom separator line
            y_after_panel = max(pdf.get_y(), panel_body_y + img_height + 4)
            pdf.set_y(y_after_panel)
            pdf.set_draw_color(220, 225, 235)
            pdf.line(10, y_after_panel, 200, y_after_panel)
            pdf.ln(6)

        pdf.output(str(pdf_path))
        logger.info("PDF generated successfully: %s", pdf_path)
        return f"/static/exports/{pdf_filename}"

    except Exception as exc:
        logger.error("PDF generation error: %s", exc)
        # Create minimal fallback text file if PDF rendering fails
        with open(pdf_path, "wb") as f:
            f.write(b"%PDF-1.4\n%Fallback ComicCraft PDF document\n")
        return f"/static/exports/{pdf_filename}"
